package com.ocean.pojo;

import java.util.Date;

public class StockInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.newPrice
     *
     * @mbggenerated
     */
    private String newprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.increase
     *
     * @mbggenerated
     */
    private String increase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.dataStr
     *
     * @mbggenerated
     */
    private String datastr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.keystr
     *
     * @mbggenerated
     */
    private String keystr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.realIndexName
     *
     * @mbggenerated
     */
    private String realindexname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.modifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.isDelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.pkid
     *
     * @return the value of stock.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.pkid
     *
     * @param pkid the value for stock.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.code
     *
     * @return the value of stock.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.code
     *
     * @param code the value for stock.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.newPrice
     *
     * @return the value of stock.newPrice
     *
     * @mbggenerated
     */
    public String getNewprice() {
        return newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.newPrice
     *
     * @param newprice the value for stock.newPrice
     *
     * @mbggenerated
     */
    public void setNewprice(String newprice) {
        this.newprice = newprice == null ? null : newprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.increase
     *
     * @return the value of stock.increase
     *
     * @mbggenerated
     */
    public String getIncrease() {
        return increase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.increase
     *
     * @param increase the value for stock.increase
     *
     * @mbggenerated
     */
    public void setIncrease(String increase) {
        this.increase = increase == null ? null : increase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.dataStr
     *
     * @return the value of stock.dataStr
     *
     * @mbggenerated
     */
    public String getDatastr() {
        return datastr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.dataStr
     *
     * @param datastr the value for stock.dataStr
     *
     * @mbggenerated
     */
    public void setDatastr(String datastr) {
        this.datastr = datastr == null ? null : datastr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.keystr
     *
     * @return the value of stock.keystr
     *
     * @mbggenerated
     */
    public String getKeystr() {
        return keystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.keystr
     *
     * @param keystr the value for stock.keystr
     *
     * @mbggenerated
     */
    public void setKeystr(String keystr) {
        this.keystr = keystr == null ? null : keystr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.realIndexName
     *
     * @return the value of stock.realIndexName
     *
     * @mbggenerated
     */
    public String getRealindexname() {
        return realindexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.realIndexName
     *
     * @param realindexname the value for stock.realIndexName
     *
     * @mbggenerated
     */
    public void setRealindexname(String realindexname) {
        this.realindexname = realindexname == null ? null : realindexname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.status
     *
     * @return the value of stock.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.status
     *
     * @param status the value for stock.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.times
     *
     * @return the value of stock.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.times
     *
     * @param times the value for stock.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.createTime
     *
     * @return the value of stock.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.createTime
     *
     * @param createtime the value for stock.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.modifyTime
     *
     * @return the value of stock.modifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.modifyTime
     *
     * @param modifytime the value for stock.modifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.isDelete
     *
     * @return the value of stock.isDelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.isDelete
     *
     * @param isdelete the value for stock.isDelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    @Override
    public String toString() {
        return "StockInfo{" +
                "pkid=" + pkid +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", newprice='" + newprice + '\'' +
                ", increase='" + increase + '\'' +
                ", datastr='" + datastr + '\'' +
                ", keystr='" + keystr + '\'' +
                ", realindexname='" + realindexname + '\'' +
                ", status='" + status + '\'' +
                ", times=" + times +
                ", createtime=" + createtime +
                ", modifytime=" + modifytime +
                ", isdelete='" + isdelete + '\'' +
                '}';
    }
}