package com.ocean.pojo;

import java.util.Date;

public class StockDaysInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.pkid
     *
     * @mbggenerated
     */
    private Integer pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.newPrice
     *
     * @mbggenerated
     */
    private String newprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.increase
     *
     * @mbggenerated
     */
    private String increase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.dataStr
     *
     * @mbggenerated
     */
    private String datastr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.keystr
     *
     * @mbggenerated
     */
    private String keystr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.realIndexName
     *
     * @mbggenerated
     */
    private String realindexname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.days
     *
     * @mbggenerated
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.times
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.modifyTime
     *
     * @mbggenerated
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_days.isDelete
     *
     * @mbggenerated
     */
    private String isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.pkid
     *
     * @return the value of stock_days.pkid
     *
     * @mbggenerated
     */
    public Integer getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.pkid
     *
     * @param pkid the value for stock_days.pkid
     *
     * @mbggenerated
     */
    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.code
     *
     * @return the value of stock_days.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.code
     *
     * @param code the value for stock_days.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.name
     *
     * @return the value of stock_days.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.name
     *
     * @param name the value for stock_days.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.newPrice
     *
     * @return the value of stock_days.newPrice
     *
     * @mbggenerated
     */
    public String getNewprice() {
        return newprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.newPrice
     *
     * @param newprice the value for stock_days.newPrice
     *
     * @mbggenerated
     */
    public void setNewprice(String newprice) {
        this.newprice = newprice == null ? null : newprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.increase
     *
     * @return the value of stock_days.increase
     *
     * @mbggenerated
     */
    public String getIncrease() {
        return increase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.increase
     *
     * @param increase the value for stock_days.increase
     *
     * @mbggenerated
     */
    public void setIncrease(String increase) {
        this.increase = increase == null ? null : increase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.dataStr
     *
     * @return the value of stock_days.dataStr
     *
     * @mbggenerated
     */
    public String getDatastr() {
        return datastr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.dataStr
     *
     * @param datastr the value for stock_days.dataStr
     *
     * @mbggenerated
     */
    public void setDatastr(String datastr) {
        this.datastr = datastr == null ? null : datastr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.keystr
     *
     * @return the value of stock_days.keystr
     *
     * @mbggenerated
     */
    public String getKeystr() {
        return keystr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.keystr
     *
     * @param keystr the value for stock_days.keystr
     *
     * @mbggenerated
     */
    public void setKeystr(String keystr) {
        this.keystr = keystr == null ? null : keystr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.realIndexName
     *
     * @return the value of stock_days.realIndexName
     *
     * @mbggenerated
     */
    public String getRealindexname() {
        return realindexname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.realIndexName
     *
     * @param realindexname the value for stock_days.realIndexName
     *
     * @mbggenerated
     */
    public void setRealindexname(String realindexname) {
        this.realindexname = realindexname == null ? null : realindexname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.status
     *
     * @return the value of stock_days.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.status
     *
     * @param status the value for stock_days.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.days
     *
     * @return the value of stock_days.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.days
     *
     * @param days the value for stock_days.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.times
     *
     * @return the value of stock_days.times
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.times
     *
     * @param times the value for stock_days.times
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.createTime
     *
     * @return the value of stock_days.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.createTime
     *
     * @param createtime the value for stock_days.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.modifyTime
     *
     * @return the value of stock_days.modifyTime
     *
     * @mbggenerated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.modifyTime
     *
     * @param modifytime the value for stock_days.modifyTime
     *
     * @mbggenerated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_days.isDelete
     *
     * @return the value of stock_days.isDelete
     *
     * @mbggenerated
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_days.isDelete
     *
     * @param isdelete the value for stock_days.isDelete
     *
     * @mbggenerated
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }
}