package com.ocean.dao;

import com.ocean.pojo.StockDaysInfo;

import java.util.List;
import java.util.Map;

public interface StockDaysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    int insert(StockDaysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    int insertSelective(StockDaysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    StockDaysInfo selectByPrimaryKey(Integer pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockDaysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_days
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockDaysInfo record);

    List<StockDaysInfo> findByCondition(Map<String, Object> params);
}